// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmhC9VYqGEURFlzVVrpze_0LutvX5UZkg',
    appId: '1:61994842346:web:7fdfb870f0cc9963bbff93',
    messagingSenderId: '61994842346',
    projectId: 'wild-explorer-flutter-app',
    authDomain: 'wild-explorer-flutter-app.firebaseapp.com',
    storageBucket: 'wild-explorer-flutter-app.appspot.com',
    measurementId: 'G-H39PGP6WE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt5qmKHmsCw4e8w0ckZfnnR7Y8P3IfQdc',
    appId: '1:61994842346:android:390963bbc11994abbbff93',
    messagingSenderId: '61994842346',
    projectId: 'wild-explorer-flutter-app',
    storageBucket: 'wild-explorer-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ZI3S2vTgRULVaKkF9DAvzIX2_d9YXiA',
    appId: '1:61994842346:ios:ce0c9c7202e81adebbff93',
    messagingSenderId: '61994842346',
    projectId: 'wild-explorer-flutter-app',
    storageBucket: 'wild-explorer-flutter-app.appspot.com',
    iosClientId: '61994842346-qa6n8da2bs2qkiu5517i4m1achd3533e.apps.googleusercontent.com',
    iosBundleId: 'vn.wx.wildExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ZI3S2vTgRULVaKkF9DAvzIX2_d9YXiA',
    appId: '1:61994842346:ios:ce0c9c7202e81adebbff93',
    messagingSenderId: '61994842346',
    projectId: 'wild-explorer-flutter-app',
    storageBucket: 'wild-explorer-flutter-app.appspot.com',
    iosClientId: '61994842346-qa6n8da2bs2qkiu5517i4m1achd3533e.apps.googleusercontent.com',
    iosBundleId: 'vn.wx.wildExplorer',
  );
}
